onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider Load_Store
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/clk
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/rst
add wave -noupdate -radix decimal /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/ls_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/ls_data_rd
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/ls_data_wr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/ls_mem
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_ls_and_cache/ls_wr_en
add wave -noupdate -divider {Reg File}
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/ra_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/ra_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/ra_rd_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/ra_rd_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rb_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rb_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rb_rd_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rb_rd_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rc_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rc_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rc_rd_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rc_rd_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/reg_array
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_wr_en_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_wr_en_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_wr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_reg_file/rt_wr_op
add wave -noupdate -divider {Odd Pipe}
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/PC_in
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/PC_out
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/PC_reg
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/RT_reg
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/clk
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/flush
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_I10
add wave -noupdate -radix decimal /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_I16
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_I18
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_I7
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_I8
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_RA
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_RB
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_RC
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_RT_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/in_ls_data
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/opcode
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/out_RT
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/out_RT_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/out_ls_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/out_ls_data
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/out_ls_wr_en
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/pc_s1
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/pc_s2
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/pc_s3
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/pc_s4
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/pc_s5
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I10
add wave -noupdate -radix hexadecimal -childformat {{{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[0]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[1]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[2]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[3]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[4]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[5]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[6]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[7]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[8]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[9]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[10]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[11]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[12]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[13]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[14]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[15]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[16]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[17]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[18]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[19]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[20]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[21]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[22]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[23]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[24]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[25]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[26]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[27]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[28]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[29]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[30]} -radix decimal} {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[31]} -radix decimal}} -subitemconfig {{/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[0]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[1]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[2]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[3]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[4]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[5]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[6]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[7]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[8]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[9]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[10]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[11]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[12]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[13]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[14]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[15]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[16]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[17]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[18]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[19]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[20]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[21]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[22]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[23]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[24]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[25]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[26]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[27]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[28]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[29]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[30]} {-radix decimal} {/spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16[31]} {-radix decimal}} /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/result
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/result_temp
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s1_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_addr_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s1_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_data_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s1_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_idx_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s1_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s2_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s3_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s4_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s5_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s6_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rf_s7_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rst
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rt_wr_en
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/rt_wr_en_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_odd_pipe/unit_idx
add wave -noupdate -divider {Even Pipe}
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/RT_reg
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/clk
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/cnt_reg
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/flush
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_I10
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_I16
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_I18
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_I7
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_I8
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_RA
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_RB
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_RC
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/in_RT_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/opcode
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/operand
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/out_RT
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/out_RT_addr
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rep_lb16_I10
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rep_lb32_I10
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rep_lb32_I16
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/result
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s1_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_addr_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s1_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_data_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s1_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_idx_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s1_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s2_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s3_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s4_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s5_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s6_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rf_s7_we
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rotate
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rotate_temp
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rst
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rt_wr_en
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/rt_wr_en_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/temp_byte_reg
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/temp_fp
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/temp_reg
add wave -noupdate -divider {FW Macro}
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_even_pipe/unit_idx
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_data_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_data_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_fw_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/ra_fw_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_data_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_data_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_fw_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rb_fw_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_data_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_data_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_fw_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rc_fw_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_addr_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_data_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s2_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s2_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s3_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s3_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s4_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s4_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s5_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s5_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s6_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s6_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s7_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rf_idx_s7_op
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rst
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rt_addr_ep
add wave -noupdate /spu_pipes_tb/u_spu_pipes_top/u_fw_macro/rt_addr_op
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {35 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {27 ns} {55 ns}
