onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /spu_tb/u_spu_top/OPCODE_LEN
add wave -noupdate /spu_tb/u_spu_top/REG_DATA_WD
add wave -noupdate /spu_tb/u_spu_top/cache_line
add wave -noupdate /spu_tb/u_spu_top/cache_wr
add wave -noupdate /spu_tb/u_spu_top/clk
add wave -noupdate /spu_tb/u_spu_top/eins1
add wave -noupdate /spu_tb/u_spu_top/eins2
add wave -noupdate /spu_tb/u_spu_top/in_I10e
add wave -noupdate /spu_tb/u_spu_top/in_I10o
add wave -noupdate /spu_tb/u_spu_top/in_I16e
add wave -noupdate /spu_tb/u_spu_top/in_I16o
add wave -noupdate /spu_tb/u_spu_top/in_I18e
add wave -noupdate /spu_tb/u_spu_top/in_I18o
add wave -noupdate /spu_tb/u_spu_top/in_I7e
add wave -noupdate /spu_tb/u_spu_top/in_I7o
add wave -noupdate /spu_tb/u_spu_top/in_I8e
add wave -noupdate /spu_tb/u_spu_top/in_I8o
add wave -noupdate /spu_tb/u_spu_top/ins_wr_en
add wave -noupdate /spu_tb/u_spu_top/ls_addr
add wave -noupdate /spu_tb/u_spu_top/ls_data_rd
add wave -noupdate /spu_tb/u_spu_top/ls_data_wr
add wave -noupdate /spu_tb/u_spu_top/ls_wr_en
add wave -noupdate /spu_tb/u_spu_top/opcode_ep
add wave -noupdate /spu_tb/u_spu_top/opcode_op
add wave -noupdate /spu_tb/u_spu_top/pc_dtof
add wave -noupdate /spu_tb/u_spu_top/pc_ftod
add wave -noupdate /spu_tb/u_spu_top/ra_addr_ep
add wave -noupdate /spu_tb/u_spu_top/ra_addr_op
add wave -noupdate /spu_tb/u_spu_top/rb_addr_ep
add wave -noupdate /spu_tb/u_spu_top/rb_addr_op
add wave -noupdate /spu_tb/u_spu_top/rc_addr_ep
add wave -noupdate /spu_tb/u_spu_top/rc_addr_op
add wave -noupdate /spu_tb/u_spu_top/rst
add wave -noupdate /spu_tb/u_spu_top/rt_addr_ep
add wave -noupdate /spu_tb/u_spu_top/rt_addr_op
add wave -noupdate -divider {New Divider}
add wave -noupdate /spu_tb/u_spu_top/u_local_store/MEM_SIZE
add wave -noupdate /spu_tb/u_spu_top/u_local_store/cache_out
add wave -noupdate /spu_tb/u_spu_top/u_local_store/cache_wr
add wave -noupdate /spu_tb/u_spu_top/u_local_store/clk
add wave -noupdate /spu_tb/u_spu_top/u_local_store/rst
add wave -noupdate /spu_tb/u_spu_top/u_local_store/ls_addr
add wave -noupdate /spu_tb/u_spu_top/u_local_store/ls_data_rd
add wave -noupdate /spu_tb/u_spu_top/u_local_store/ls_data_wr
add wave -noupdate /spu_tb/u_spu_top/u_local_store/ls_mem
add wave -noupdate /spu_tb/u_spu_top/u_local_store/ls_wr_en
add wave -noupdate -divider {New Divider}
add wave -noupdate /spu_tb/u_spu_top/u_fetch/blk_offset
add wave -noupdate /spu_tb/u_spu_top/u_fetch/blk_tag
add wave -noupdate /spu_tb/u_spu_top/u_fetch/blk_valid
add wave -noupdate /spu_tb/u_spu_top/u_fetch/branch_taken
add wave -noupdate /spu_tb/u_spu_top/u_fetch/cache
add wave -noupdate /spu_tb/u_spu_top/u_fetch/cache_line
add wave -noupdate /spu_tb/u_spu_top/u_fetch/cache_wr
add wave -noupdate /spu_tb/u_spu_top/u_fetch/chit
add wave -noupdate /spu_tb/u_spu_top/u_fetch/chit1
add wave -noupdate /spu_tb/u_spu_top/u_fetch/chit2
add wave -noupdate /spu_tb/u_spu_top/u_fetch/clk
add wave -noupdate /spu_tb/u_spu_top/u_fetch/cmiss
add wave -noupdate /spu_tb/u_spu_top/u_fetch/eins1
add wave -noupdate /spu_tb/u_spu_top/u_fetch/eins2
add wave -noupdate /spu_tb/u_spu_top/u_fetch/last_used
add wave -noupdate /spu_tb/u_spu_top/u_fetch/offset
add wave -noupdate -radix decimal /spu_tb/u_spu_top/u_fetch/pc
add wave -noupdate /spu_tb/u_spu_top/u_fetch/pc_in
add wave -noupdate /spu_tb/u_spu_top/u_fetch/pc_out
add wave -noupdate /spu_tb/u_spu_top/u_fetch/rst
add wave -noupdate /spu_tb/u_spu_top/u_fetch/tag
add wave -noupdate -divider {New Divider}
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/MASK1
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/MASK2
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/OPCODE_LEN
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/PC_in
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/PC_out
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/PC_reg
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/REG_ADDR_WD
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/REG_DATA_WD
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/RT_reg
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/cache_wr
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/clk
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/flush
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_I10
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_I16
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_I18
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_I7
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_I8
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_RA
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_RB
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_RC
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_RT_addr
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/in_ls_data
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/opcode
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/out_RT
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/out_RT_addr
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/out_ls_addr
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/out_ls_data
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/out_ls_wr_en
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/pc_s1
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/pc_s2
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/pc_s3
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/pc_s4
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/pc_s5
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/repc_lb32_I10
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/repc_lb32_I16
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/result
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/result_temp
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s1_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s2_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s3_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s4_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s5_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s6_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_addr_s7_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s1_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s2_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s3_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s4_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s5_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s6_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_data_s7_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s1_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s2_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s3_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s4_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s5_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s6_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_idx_s7_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s1_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s2_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s3_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s4_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s5_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s6_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rf_s7_we
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rst
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rt_wr_en
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/rt_wr_en_op
add wave -noupdate /spu_tb/u_spu_top/u_spu_pipes_top/u_odd_pipe/unit_idx
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {84 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {128 ns}
